### ISSUE TITLE
CAPTURED_IMAGE_NAME override

### ISSUE THREAD

**Issue by goors** [tuanchauict/IntentChooser#1]
How can I override this not to be static "capturedImageResult.jpeg"?
So i can do something like 

```
long time= System.currentTimeMillis(); 
CAPTURED_IMAGE_NAME = String.valueOf(time)+".jpg"
```

Can you update your repo/lib and remove `final` from` public static final String`?

**Comment by tuanchauict** [comment]
I will change it next version

**Comment by tuanchauict** [comment]
Update to version `0.1.7`
```java
ImageChooserMaker.setCapturedImageName(newName)
```

**Comment by goors** [comment]
perfect! thanks!
